# Generated by Django 4.2.1 on 2023-05-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0005_product_delete_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Name',
            field=models.CharField(max_length=30),
        ),
    ]
