# Generated by Django 4.2.1 on 2023-05-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0006_alter_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=30)),
                ('category_size', models.IntegerField(default=0)),
                ('category_description', models.TextField(max_length=200)),
                ('category_image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='prod_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_category',
            field=models.ManyToManyField(to='USERS.category'),
        ),
    ]
