# Generated by Django 4.2.1 on 2023-05-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0007_category_product_prod_img_product_prod_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_description',
            field=models.TextField(max_length=1000),
        ),
    ]
