# Generated by Django 4.2.1 on 2023-05-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0008_alter_category_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(null=True, upload_to='category_pics'),
        ),
    ]
