# Generated by Django 4.2.1 on 2023-05-31 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0009_alter_category_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_category',
            field=models.ManyToManyField(related_name='product_set', to='USERS.category'),
        ),
    ]
