# Generated by Django 4.2.1 on 2023-06-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0010_alter_product_prod_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_category',
            field=models.ManyToManyField(to='USERS.category'),
        ),
    ]
