# Generated by Django 4.2.1 on 2023-06-18 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0013_alter_cart_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
