# Generated by Django 4.2.1 on 2023-07-06 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0014_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_size',
        ),
    ]
