# Generated by Django 4.2.1 on 2023-06-18 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('USERS', '0014_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_addr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=50)),
                ('stree_addr', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
                ('Pin_code', models.IntegerField()),
                ('phone_number', models.CharField(max_length=10)),
                ('Country', models.CharField(max_length=30)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('order_addr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order_addr')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USERS.product')),
            ],
        ),
    ]
