# Generated by Django 4.2.1 on 2023-06-20 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0014_delete_order'),
        ('orders', '0002_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=300)),
                ('paid', models.BooleanField(default=False)),
                ('order_addr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order_addr')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USERS.product')),
            ],
        ),
    ]
