# Generated by Django 4.2.1 on 2023-06-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0014_delete_order'),
        ('orders', '0004_order_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ManyToManyField(to='USERS.product'),
        ),
    ]
